### ISSUE TITLE
Download completed with incomplete Data

### ISSUE THREAD

**Issue by IIIPeAceIII** [filecxx/FileCentipede#298] opened 2022-07-16 07:42 UTC
I download a file from https link but it gets finished without downloading whole data. Due to this it gets corrupted as I open that file
![fe](https://user-images.githubusercontent.com/90670189/179345469-70f97f5e-0718-427e-a400-d61e124bab37.png)
.

**Comment by filecxx** [comment] 2022-07-16 08:13
I believe this is a new bug for HTTP max-connections over 64, could you provide the URL address?

**Comment by IIIPeAceIII** [comment] 2022-07-16 08:24
> I believe this is a new bug for HTTP max-connections over 64, could you provide the URL address?

https://ww7.zeroupload.com/a2164f729d117bb4/Adobe-After-Effects-2022-v22.5.0.53-x64.rar?download_token=557dd89863f34d615df3a5f4ff196702617f357018634fffb1176758f42ee95b

**Comment by filecxx** [comment] 2022-07-16 08:56
I just tested this address with 128 connections, during downloading, my IP address has been banned for few times, which was probably caused by this, for the HTTP task, recommended max-connections is 16, but I will fix this in the next version.

**Comment by IIIPeAceIII** [comment] 2022-07-16 12:12
oh great, thanks!

**Comment by filecxx** [comment] 2022-08-01 11:30
It has been fixed in FileCentipede 2.3

**Closed by filecxx** 2022-08-01 11:30 UTC
